
# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Letsdetour' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  pod 'NVActivityIndicatorView'
	pod 'SDWebImage'
  pod 'lottie-ios'
  pod "FlagPhoneNumber"
  pod 'Cosmos', '~> 23.0'
  pod 'GooglePlaces'
  pod 'FBSDKLoginKit'
  pod 'GoogleSignIn'
  pod 'LocationPicker'
  pod 'Firebase'
  pod 'FSCalendar'

  pod 'Firebase/Analytics'
  pod 'Firebase/DynamicLinks'
end
